name: C/C++ CI

on:
  push:
    branches:
      - '**' # matches every branch
  pull_request:
    branches:
      - '**' # matches every branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: prerequisites
      run: sudo apt install libboost-filesystem-dev && sudo apt install libboost-test-dev && sudo apt install z3
    - name: mkdir build
      run: mkdir build
    - name: make debug
      run: make debug
    - name: make test
      run: VATA_PATH=$PWD/vata make test
