name: C/C++ CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  # setup:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: sudo apt-get install libboost-filesystem-dev && sudo apt-get install libboost-test-dev && sudo apt-get install z3
  build-and-test-debug:
    # needs: setup
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install libboost-filesystem-dev && sudo apt-get install libboost-test-dev && sudo apt-get install z3
    - uses: actions/checkout@v4
    - run: mkdir build
    - run: make debug
    - run: make test
  build-and-test-release:
    # needs: setup
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install libboost-filesystem-dev && sudo apt-get install libboost-test-dev && sudo apt-get install z3
    - uses: actions/checkout@v4
    - run: mkdir build
    - run: make release
    - run: make test
