name: C/C++ CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  # setup:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: sudo apt-get install libboost-filesystem-dev && sudo apt-get install libboost-test-dev && sudo apt-get install z3
  build-debug:
    # needs: setup
    runs-on: ubuntu-latest
    steps:
    - with:
      apt-get: libboost-filesystem-dev libboost-test-dev z3
    - run: git clone https://github.com/alan23273850/AutoQ.git
    - run: mv AutoQ AutoQ-debug
    - run: cd AutoQ-debug && mkdir build && make debug
  test-debug:
    needs: build-debug
    runs-on: ubuntu-latest
    steps:
    - run: cd AutoQ-debug && make test
  build-release:
    # needs: setup
    runs-on: ubuntu-latest
    steps:
    - with:
      apt-get: libboost-filesystem-dev libboost-test-dev z3
    - run: git clone https://github.com/alan23273850/AutoQ.git
    - run: mv AutoQ AutoQ-release
    - run: cd AutoQ-release && mkdir build && make release
  test-release:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
    - run: cd AutoQ-release && make test
